Fix reconnect logic
Tinkoff/mbclient pull request #125
Opened 2022-11-30 06:32 UTC by sgrigorev

The handleConnectionClose may be called several times in short period of time.This may lead to several consumers is binded to one queue. We set synchronously the connection status to "connecting" and check it in the beginnig of the handler in order to fix the issue.

2022-11-30 09:30 UTC, alexkvak requested changes

2022-11-30 09:54 UTC, sgrigorev commented on src/service.ts
> -    this.emit(ConnectionStatus.DISCONNECTED);
The event is emitted in `this.setConnectionStatus` function. So, there is nothing has been changed.

2022-11-30 10:09 UTC, alexkvak approved these changes

2022-12-01 10:49 UTC, qwerty2323 approved these changes

2022-12-01 11:18 UTC, leoShabalkin approved these changes

2022-12-01 11:22 UTC, merged

2022-12-01 11:26 UTC, alexkvak commented
:tada: This PR is included in version 3.2.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/mbclient/v/3.2.1)
- [GitHub release](https://github.com/Tinkoff/mbclient/releases/tag/v3.2.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: